version: "3.8"

services:
  backend:
    build:
      context: ./backend # Dossier contenant le Dockerfile pour le service backend
    ports:
      - "5000:5000" # Exposer Flask sur le port 5000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80" # Exposer Nginx sur le port 80
    depends_on:
      - backend # Attendre que le service backend soit lancé
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
